// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE7G8pbpzjqwQCbbuEo36k-FyKyR1IkPE',
    appId: '1:631447569906:web:35eaaabcad853d56da976b',
    messagingSenderId: '631447569906',
    projectId: 'identplant-f3783',
    authDomain: 'identplant-f3783.firebaseapp.com',
    storageBucket: 'identplant-f3783.appspot.com',
    measurementId: 'G-XYHMY88XS4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXM9vggVkJbnjl1FDsy2HJjMvYmroAbqU',
    appId: '1:631447569906:android:bfed0298c5a4d471da976b',
    messagingSenderId: '631447569906',
    projectId: 'identplant-f3783',
    storageBucket: 'identplant-f3783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeIWYC3UdK-gJtS5xBNvWeX1O4SmRwf0U',
    appId: '1:631447569906:ios:8b0c67109cbb1f59da976b',
    messagingSenderId: '631447569906',
    projectId: 'identplant-f3783',
    storageBucket: 'identplant-f3783.appspot.com',
    iosClientId: '631447569906-6bll6qvffokgmpi897db6t5bq9l8crlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.identPlant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeIWYC3UdK-gJtS5xBNvWeX1O4SmRwf0U',
    appId: '1:631447569906:ios:8b0c67109cbb1f59da976b',
    messagingSenderId: '631447569906',
    projectId: 'identplant-f3783',
    storageBucket: 'identplant-f3783.appspot.com',
    iosClientId: '631447569906-6bll6qvffokgmpi897db6t5bq9l8crlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.identPlant',
  );
}
